# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
import numpy as np

# Define matrix A
A = np.arange(1, 16).reshape(3, 5)

print("Matrix A:")
print(A)
print("\nNumber of dimensions (ndim):", A.ndim)
print("shape:", A.shape)
print("size (total number of elements):", A.size)
print("datatype of elements:", A.dtype)

Matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Number of dimensions (ndim): 2
shape: (3, 5)
size (total number of elements): 15
datatype of elements: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

In [6]:
import numpy as np
B = np.arange(1,10).reshape(3,3)
C = np.ones((3,3)) * 2

print("Matrix B")
print(B)
print("\nMatrix C:")
print(C)

subtraction = B - C
print("\nElement-wise subtraction (B - C):")
print(subtraction)

elementwise_multiplication = B * C
print("\nElement-wise Multiplication (B * C):")
print(elementwise_multiplication)

matrix_multiplication = B @ C
print("\nMatrix Multiplication (B @ C):")
print(matrix_multiplication)

Matrix B
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix C:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Element-wise subtraction (B - C):
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Element-wise Multiplication (B * C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication (B @ C):
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

In [7]:
import numpy as np

B = np.arange(1, 10).reshape(3, 3)
print("Matrix B:")
print(B)

exp_B = np.exp(B)
print("\nElement-wise Exponention (np.exp(B)):")
print(exp_B)

min_B = B.min()
print("\nMinimum value in B:", min_B)

min_B_rows = B.min(axis=1)
print("\nMinimum value in each row:", min_B_rows)

min_B_cols = B.min(axis=0)
print("\nMinimum value in each column:", min_B_cols)

index_min_B = np.argmin(B)
print("\nIndex of minimum value in B (flattened):", index_min_B)

index_min_B_2d = np.unravel_index(index_min_B, B.shape)
print("2D Index of minimum value in B:", index_min_B_2d)

index_min_B_rows = B.argmin(axis=1)
print("\nIndices of minimum values in each row:", index_min_B_rows)

sum_B = B.sum()
print("\nSum of all elements in B:", sum_B)

mean_B_cols = B.mean(axis=0)
print("\nMean of each column in B:", mean_B_cols)

median_B_cols = np.median(B, axis=0)
print("\nMedian of each column in B:", median_B_cols)


Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Element-wise Exponention (np.exp(B)):
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in B: 1

Minimum value in each row: [1 4 7]

Minimum value in each column: [1 2 3]

Index of minimum value in B (flattened): 0
2D Index of minimum value in B: (0, 0)

Indices of minimum values in each row: [0 0 0]

Sum of all elements in B: 45

Mean of each column in B: [4. 5. 6.]

Median of each column in B: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

In [8]:
when fewer indices than the number of axes (dimensions) in a NumPy array during slicing, the missing indices are treated as complete slices (:) for those axes. This means that the unspecified axes are fully included in the selection.

SyntaxError: invalid syntax (1136249604.py, line 1)

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [ ]:
for i in A:
    print(i)

In [9]:
import numpy as np

A = np.arange(1,16).reshape(3,5)
print("Matrix A:")
print(A)

print("\nIterating element-wise:")
for element in A.flat:
    print(element)
    

Matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Iterating element-wise:
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [ ]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

In [10]:
Axis 0: Diffirentiates between the two main blocks/metrices
Axis 1: Defferentiates between the rows within each block.
Axis 2: Defferentiates between the elements within each row.

SyntaxError: invalid syntax (3872496970.py, line 1)

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [11]:
import numpy as np

def add_mult_matrices(matrix1, matrix2, operation):
    
    

    if not isinstance(matrix1, np.ndarray):
        raise TypeError("matrix1 must be a numpy.ndarray.")
    if not isinstance(matrix2, np.ndarray):
        raise TypeError("matrix2 must be a numpy.ndarray.")
    
    
    if operation not in ['add', 'multiply']:
        raise ValueError("operation must be either 'add' or 'multiply'.")
    
    if operation == 'add':
        
        if matrix1.shape != matrix2.shape:
            raise ValueError(f"Matrices must have the same shape for addition. "
                             f"matrix1 shape: {matrix1.shape}, matrix2 shape: {matrix2.shape}")
        result = matrix1 + matrix2
        print(f"Addition Result:\n{result}")
        return result
    
    elif operation == 'multiply':
        
        if matrix1.ndim != 2 or matrix2.ndim != 2:
            raise ValueError("Both matrices must be two-dimensional for matrix multiplication.")
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError(f"For matrix multiplication, the number of columns in matrix1 must equal the number of rows in matrix2. "
                             f"matrix1 shape: {matrix1.shape}, matrix2 shape: {matrix2.shape}")
        result = matrix1 @ matrix2  
        print(f"Multiplication Result:\n{result}")
        return result

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

In [18]:
import numpy as np

v1 = np.arange(4) 
v2 = v1[-2:] 

print("v1:", v1)
print("v2:", v2)

print("\nBase Attributes:")
print("v1.base:",v1.base)
print("v2.base:",v2.base)

print("\nData Ownership Flags")
print("v1 owns data", v1.flags['OWNDATA'])
print("v2 owns data", v2.flags['OWNDATA'])

v2[-1] = 123

print("\nModified Arrays:")
print("v1:",v1)
print("v2:",v2)

v1: [0 1 2 3]
v2: [2 3]

Base Attributes:
v1.base: None
v2.base: [0 1 2 3]

Data Ownership Flags
v1 owns data True
v2 owns data False

Modified Arrays:
v1: [  0   1   2 123]
v2: [  2 123]
